### PR TITLE
bytestring 0.12

### PR DESCRIPTION
**Pull request by andreasabel**
- Bump Haskell CI to latest GHCs: 9.6.2 9.2.8
- v1.3.2.1-r1: allow bytestring-0.12

### CODE REVIEW

**Comment by andreasabel** [comment]
Pushed to master in 771ac3badadc4d34002be26916b0acd11509d0f5

**Comment by phadej** [comment]
Same question as with `cassava`, `parsec` depends on `text` and neither allow `bytestring-0.12`. Have you tested that they work?

**Comment by andreasabel** [comment]
I tested with `constraints: bytestring >= 0.12` and `allow-newer: bytestring` locally.  
`cabal-plan fingerprint` shows just one entry for `bytestring`:
```
<hash> G bytestring-0.12.0.0
```
I concluded this was enough evidence.

I could have added a `constraint-set` for `bytestring-0.12` to the CI, but now I realize that this only checks the build, but does not run the tests: https://github.com/haskell/base64-bytestring/pull/50/files#r1257414879
Is there a way to instrument the `constraint-set` step to also run the tests?

**Comment by phadej** [comment]
> Is there a way to instrument the constraint-set step to also run the tests?

https://github.com/haskell-CI/haskell-ci/blob/782c6f634b44ccd8f55c60d8058673bdfc176e23/cabal.haskell-ci#L106-L115

**Comment by andreasabel** [comment]
Thanks for the pointer, @phadej!

Unfortunately, `constraint-set` does not recognise `allow-newer`, is there a way to place `allow-newer: bytestring` in the `cabal.project` for the `constraint-set`?

**Comment by phadej** [comment]
> Unfortunately, constraint-set does not recognise allow-newer

And I don't see a reason to make it.

Add `allow-newer` to the whole `cabal.project`. The `bytestring` is pinned to `installed` version by the step building with bundled libraries, and then the constraint set will build separately. (Or if the library weren't boot library, you probably should have constraint sets for various major versions anyway to ensure that the old one is tested when support elsewhere catches up, and then `cabal-install` won't pick old one if not explicitly asked for).

**Pull request closed without merging**
